export const bookStyles = {
  page: {
    flex: 1,
    position: "relative",
    background: "#fffef0",
    overflow: "hidden",
    border: "2px solid #d4c5a9",
    boxShadow:
      "-8px 8px 25px rgba(0,0,0,0.2), inset -30px 0 40px rgba(0,0,0,0.08)",
    transition: "transform 0.3s ease",
    p: "60px 50px",
    borderRadius: "16px",
  },
  lines: {
    position: "absolute",
    inset: 0,
    background:
      "repeating-linear-gradient(0deg, transparent, transparent 31px, rgba(212,197,169,0.3) 31px, rgba(212,197,169,0.3) 32px)",
    pointerEvents: "none",
  },
  margin: {
    position: "absolute",
    top: "8%",
    bottom: "8%",
    left: "50px",
    width: "3px",
    background: "rgba(220,160,160,0.4)",
    pointerEvents: "none",
  },
  shadow: {
    position: "absolute",
    right: 0,
    top: 0,
    height: "100%",
    width: "80px",
    background: "linear-gradient(to left, rgba(0,0,0,0.25), transparent)",
    pointerEvents: "none",
  },
};

export const generalObjects = [
  "Laptop",
  "Mug",
  "Notebook",
  "Pen",
  "Phone",
  "Plant",
  "Chair",
  "Table",
  "Backpack",
  "Shoes",
  "Lamp",
  "Water Bottle",
  "Mirror",
  "Socks",
  "Pillow",
  "Clock",
  "Window",
  "Book",
  "Cushion",
  "Curtain",
  "Tree",
  "Bird",
  "Car",
  "Cloud",
  "Grass",
  "Sky",
  "Bicycle",
  "Dog",
  "Cat",
  "Sunlight",
  "Person",
  "Bus",
  "Building",
  "Road",
  "Lamp Post",
  "Traffic Light",
  "Sun",
  "Bag",
  "Bench",
  "Flower",
  "Signboard",
];
